# Artificial Intelligence - Lab Project - Part 2

## Building a "Traditional" RAG system and evaluating it

**Names:**   Αικατερίνα Γεωγράνα
**Student IDs:**   ge20097
**Team ID:**    Ομάδα 28

This project has two steps:
One is about designing a traditional RAG system on the movie script "12 Angry Men". The chunk retrieval is based on a combination of keyword and vector search.

The second is about evaluating your system based on a dataset which will be common with all other teams and is made up of a few questions you provided in Part 1 of the Assignment.

## Deliverables:
You will be designing a basic RAG system in this notebook. The necessary python libraries will be given to you for each task but you will have to write the actual code. Specific instructions will be given above each cell.
You only need to implement the code that will be instructed in comments in the code in the notebook's cells.

## What you need to upload
### A zip file named: ``` AI_Assignment_2_Team_{REPLACE WITH TEAMID}.zip" ``` containing:

- This notebook completed and with the cell outputs (named: `AI_Assignment_2_Team_{REPLACE WITH TEAMID}_notebook.ipynb` )
- The csv evaluation file (named: `AI_Assignment_2_Team_{REPLACE WITH TEAMID}_evaluation.csv`

## Please be careful with file naming and format!

# Visualize the dataset

To start with, upload the dataset in Google Colab. Then you can print the first lines to make sure it is correct.

In [16]:
import pandas as pd

# Load the dataset
df = pd.read_csv("dataset.csv")

display(df.head())

,Question,Correct Answer,Page References,Explanation
0,What type of train passes by the apartment rig...,An el train (elevated train).,26,This requires retrieving a specific environmen...
1,"According to the boy's alibi, where did he cla...",He claimed to be at the movies.,25,Retrieval of a specific plot point established...
2,What does the sign on the first door of the co...,Court of General Sessions. Part I,3,Fact explicitly stated in the script in the de...
3,What pattern does Juror #3 draw on the same sh...,tic-tac-toe pattern,64,Fact explicitly stated in the script. The info...
4,Which Juror says that he's lived in a slum all...,Juror #5,31,Fact explicitly stated in the script on page 31

# Building a Traditional RAG System: 12 Angry Men

In this exercise, we are going to build a basic Retrieval-Augmented Generation (RAG) system from scratch. Our target data is the script for the movie *12 Angry Men*.

A Large Language Model (LLM) alone might not know specific details about this script. To fix this, we will:
1. Download the raw PDF of the script and extract its text.
2. Break the script down into smaller pieces (chunks).
3. Store these chunks in Keyword (BM25) and Vector (FAISS) databases.
4. Search both databases when a question is asked.
5. Provide the retrieved chunks to the LLM so it can answer the question accurately.

# Step 1: Install required libraries
In this first step, we install all the necessary Python packages for building our retrieval and language model pipeline.

The command below uses `pip` to quietly (`-q`) install:

- **transformers** → for loading and using large language models (LLMs)
- **accelerate** → for efficient model execution (especially on GPUs)
- **sentence-transformers** → for generating text embeddings
- **faiss-cpu** → for fast similarity search in vector databases
- **rank_bm25** → for traditional keyword-based retrieval
- **pandas** → for handling and analyzing tabular data
- **PyMuPDF** → for reading and processing PDF documents

> Run this cell once before continuing with the rest of the notebook.

In [17]:
!pip install -q transformers accelerate sentence-transformers faiss-cpu rank_bm25 pandas PyMuPDF

## Step 2: Data Ingestion & Document Chunking

Before we can search through our movie script, we need to load the PDF and break it down into smaller, digestible pieces called **chunks**.

Why do we chunk?
1. **Context Limits:** Large Language Models (LLMs) have a maximum context window. We can't feed a 100-page PDF into the prompt all at once.
2. **Retrieval Accuracy:** If our search system returns massive blocks of text, the LLM might get distracted by irrelevant information ("lost in the middle" effect). Smaller, focused chunks lead to more accurate answers. How many chunks we provide the LLM is not set of course, depending on the LLM capabilities we can give smaller or larger number of chunks.


### Chunking for this assignment: Structural Chunking (Page-Based)
Instead of arbitrary word counts, we could use the document's natural structure. Of course there are other ways to create the chunks as there is no requirement for them to be of equal size.

In the cell below, we will:
1. Download the script for *12 Angry Men*.
2. Iterate through the PDF **page-by-page** using `PyMuPDF`.
3. Save each page as its own chunk.

> **Tip for RAG:** Notice how we inject `--- Page X ---` at the top of every chunk. This is a form of **metadata enrichment**. By embedding the page number directly into the text, we give the LLM the ability to cite its sources when answering the user!

In [18]:
import requests
import fitz  # PyMuPDF

# 1. Download the movie script PDF
url = "https://f004.backblazeb2.com/file/screenplays/posts/12-angry-men-1957/scripts/12%20Angry%20Men%20-%20Release.pdf"
pdf_path = "12_angry_men.pdf"

print("Downloading the script PDF...")
response = requests.get(url)
with open(pdf_path, "wb") as f:
    f.write(response.content)
print("Download complete!")

# 2. Extract text and chunk by page
print("Extracting text from PDF by page...")
doc = fitz.open(pdf_path)

chunks = []

for page_num, page in enumerate(doc):
    page_text = page.get_text().strip()

    # We only add the page if it actually contains text (skips blank pages)
    if page_text:
        # Pro-tip: Adding the page number to the chunk helps the LLM cite its sources!
        chunk_content = f"--- Page {page_num + 1} ---\n{page_text}"
        chunks.append(chunk_content)

print(f"Created {len(chunks)} chunks from {len(doc)} pages.")

# Let's peek at an example chunk
print("\n--- Example Chunk [10] (Page 11) Preview ---")
print(chunks[10][:500]) # Printing the first 500 characters of the 11th chunk
print("--------------------------------------------")

Downloading the script PDF...
Download complete!
Extracting text from PDF by page...
Created 149 chunks from 149 pages.

--- Example Chunk [10] (Page 11) Preview ---
--- Page 11 ---
11.
#3
(smiling)
I didn't get a chance to look at the
papers today.
#4
I was just wondering how the market
closed.
#3
(pleasantly)
I wouldn't knew. Say, are you on the
exchange or something.
#4
I'm a broker.
#3
Well that's very interesting.
Listen, maybe you can answer a
question for me. I have an uncle
who’s been playing around with some
Canadian stuff...
The foreman turns around, and, as if it is an effort, calls
out loudly to the others.
FOREMAN
All right, gentlemen. Let’s ta
--------------------------------------------

## Step 4: Building the Retrieval Databases

To enable accurate information retrieval within our RAG system, we need efficient methods to parse and search our text chunks. In this section, you will set up the core components of a hybrid search system by implementing two distinct search strategies: a sparse keyword database and a dense vector database.

*(Note: Assume the variable `chunks`, a list of text strings, is already available in your environment from the previous steps.)*

### 1. Keyword Search (BM25): Lexical Matching
BM25 operates as an advanced algorithmic version of a traditional keyword index.
* **Mechanism:** It identifies exact word matches between the user's query and the text chunks using a statistical scoring framework (based on Term Frequency-Inverse Document Frequency). It heavily weights rare, highly specific terms (e.g., "photosynthesis") while discounting common vocabulary (e.g., "the," "and").
* **Strengths:** Highly effective for retrieving specific entities, proper names, exact quotes, or strict technical jargon.
* **Limitations:** Relies strictly on lexical matching. It will fail to retrieve a chunk that exclusively uses a synonym (e.g., a query for "automobile" will not match a chunk only containing "car").

### 2. Vector Search (FAISS): Semantic Matching
Vector search identifies relevant information based on underlying meaning and context rather than exact phrasing.
* **Mechanism:** Using an embedding model, we translate text chunks into high-dimensional numerical vectors (embeddings). Texts with similar semantic meanings are positioned closer together in this mathematical space. FAISS (Facebook AI Similarity Search) rapidly calculates the spatial distance between these vectors.
* **Strengths:** Excels at understanding context and conceptual relationships (e.g., a query for "canines playing" will successfully retrieve a text chunk about "dogs fetching a ball").
* **Limitations:** Because it evaluates broad meaning, it can be overly generalized and underperform when a query requires a rigid, exact match (such as a specific user ID).

---

### Your Tasks:

**1. Keyword Database (BM25)**
* Tokenize the text `chunks` by splitting them by simple spaces.
* Initialize a `BM25Okapi` object with these tokenized chunks.

**2. Vector Database (FAISS)**
* Load the `'all-MiniLM-L6-v2'` embedding model using `SentenceTransformer`.
* Use this model to encode our `chunks` into vector embeddings.
* Find the dimensionality of these newly created embeddings.
* Create a `faiss.IndexFlatL2` index using that exact dimension.
* Add your embeddings to the FAISS index (remember to convert them to a NumPy array if they aren't already).

In [19]:
from rank_bm25 import BM25Okapi
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np

print("Building Keyword Database (BM25)...")

# TODO: Tokenize 'chunks' (simple space splitting)
tokenized_chunks = [chunk.split() for chunk in chunks]

# TODO: Initialize the BM25Okapi object
bm25 = BM25Okapi(tokenized_chunks)

print("Building Vector Database (FAISS)...")

# TODO: Load the 'all-MiniLM-L6-v2' embedding model
embedder = SentenceTransformer('all-MiniLM-L6-v2')

# TODO: Convert the text chunks into vector embeddings
embeddings = embedder.encode(chunks)

# TODO: Get the dimension of the embeddings
dimension = embeddings.shape[1]

# TODO: Create a FAISS IndexFlatL2 index using the dimension ("IndexFlatL2" function)
vector_db =  faiss.IndexFlatL2(dimension)

# TODO: Add the numpy array of embeddings to the FAISS index
vector_db.add(np.array(embeddings))

Building Keyword Database (BM25)...
Building Vector Database (FAISS)...

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

## Step 5: The Hybrid Retriever

Now it is time to build the engine of our RAG system. You will write a function that takes a user's query, searches *both* of our databases, and returns the most relevant context.

Because BM25 (lexical) and FAISS (semantic) excel at different types of matching, using them together yields much better results than using either alone.

**Your Task:**
Create a `hybrid_retrieve` function that executes the following pipeline:
1. **Keyword Search:** Tokenize the incoming query, score it against your `bm25` database, and extract the indices of the top-scoring chunks.
2. **Vector Search:** Encode the query using your `embedder`, search the `vector_db`, and extract the indices of the closest vectors.
3. **The Fusion Challenge (Your Choice):** You now have two lists of "top indices." You must design a way to combine them into a single, final list of indices.
    * *Basic Approach:* Combine the lists and use a Python `set` to remove duplicates.
    * *Advanced Approach (Optional):* Implement a scoring algorithm like **Reciprocal Rank Fusion (RRF)** to mathematically weigh and re-rank the indices based on their positions in both original lists.
4. **Fetch Context:** Map your final combined indices back to the original `chunks` list to get the actual text.

### Expected Outcome
Your function should return a Python **list of text strings** (the actual text chunks). When you run the test query at the bottom of the cell, it should print the relevant text chunks that best answer the question.

In [20]:
def hybrid_retrieve(query, top_k=2):
    """
    Retrieves top chunks using BM25 and Vector Search, then combines the results.
    """

    # --- 1. Keyword Search (BM25) ---
    # TODO: Tokenize the query (split by spaces)
    tokenized_query = query.split()

    # TODO: Get scores for the query from the 'bm25' object ("get_scores" function)
    bm25_scores = bm25.get_scores(tokenized_query)

    # TODO: Get the indices of the top-scoring chunks
    bm25_top_indices = np.argsort(bm25_scores)[::-1][:top_k * 5]


    # --- 2. Vector Search (FAISS) ---
    # TODO: Encode the query into a vector using your 'embedder'
    query_embedding = embedder.encode(query)


    # TODO: Search the 'vector_db' to get the top indices ("search" function )
    # Fetch more top initially to allow for better fusion and deduplication
    distances, faiss_top_indices = vector_db.search(np.array([query_embedding]).astype('float32'), top_k * 5)
    # Hint: FAISS returns a 2D array, you may need to extract the first element (e.g., [0].tolist())
    faiss_top_indices = faiss_top_indices[0].tolist()

    # --- 3. Combine ---
     # TODO: Implement your strategy to combine 'bm25_top_indices' and 'faiss_top_indices'.
    # You can use simple deduplication (sets), alternating selection, or advanced algorithms like RRF.
    # Ensure your final list is no longer than the desired output size (though you may fetch more initially).
    # Implement the basic fusion strategy: Combine lists and use a set to remove duplicates
    combined_indices_set = set(bm25_top_indices).union(set(faiss_top_indices))

    # Convert back to a list and ensure indices are valid within the range of 'chunks'
    # Sort to maintain some consistency, though the order might not be strictly ranked after set operation
    valid_combined_indices = sorted([idx for idx in list(combined_indices_set) if 0 <= idx < len(chunks)])

    # Limit to the desired top_k
    final_combined_indices = valid_combined_indices[:top_k]

    # --- 4. Fetch the Text ---
    # TODO: Fetch the actual text strings from the original 'chunks' list using your final indices
    retrieved_chunks = [chunks[idx] for idx in final_combined_indices]

    return retrieved_chunks


# ==========================================
# You can test your hybrid retrieval function with a sample query. Adjust the query and top_k as needed to see how your fusion strategy performs.
# ==========================================
test_query = "Who had a cold?"

# Feel free to adjust top_k to see how your fusion strategy handles more chunks
results = hybrid_retrieve(test_query, top_k=2)

print(f"Found {len(results)} relevant chunks for the test query.\n")
for i, chunk in enumerate(results):
    print(f"--- Chunk {i + 1} ---")
    print(chunk)
    print()

Found 2 relevant chunks for the test query.

--- Chunk 1 ---
--- Page 2 ---
2.
Juror #9: 70 years old. Retired. A mild, gentle old man, long
since defeated by life, and now merely waiting to die. A man
who recognizes himself for what he is, and mourns the days
when it would have been possible to be courageous without
shielding himself behind his many years. From the way he take
pills whenever he is excited, it is obvious that he has a
heart condition.
Juror #10: 46 years old. Garage owner. An angry, bitter man.
A man who antagonizes almost at sight. A bigot who places no
values on any human life save his own. A man who has been no
where and is going nowhere and knows it deep within him. He
has a bad cold and continually blows his nose, sniffs a ben-
zedrine inhaler, etc.
Juror #11: 48 years old. Watchmaker. A refugee from Europe
who has come to this country in 1941. A man who speaks with
an accent and who is ashamed, humble, almost subservient to
the people around him, but a man who will honestly seek
Justice because he has suffered through so much injustice.
Juror #12: 30 years old. Advertising man. A slick, bright
advertising man who thinks of human beings in terms of
percentages, graphs and polls, and has no real understanding
of people. A superficial snob, but trying to be a good
fellow. Throughout the film he doodles on a scratch pad.
AND
THE JUDGE
THE COURT CLERK
THE GUARD
THE two alternate JURORS
ADD ( IF DESIRED )
THE COURT STENOGRAPHER
FADE IN:
EXT. LONG SHOT - N. Y. - COURT OF GENERAL SESSIONS - DAY
1
1
A large, imposing tallying, gray, impressive as a background
for the comings and goings of a number of ordinary people on
an ordinary day. Camera holds on steps and building front
from a distance and then dollies in slowly.
DISSOLVE TO:

--- Chunk 2 ---
--- Page 10 ---
10.
Yeah! And what about the business
with the knife- I mean asking grown-
up people to believe that kind of
bushwash.
#8 turns during these lines to look at #7.
MEDIUM SHOT - #7 AND #10
#10 sits in a chair not at table, #7 stands over him mopping
his brow
#10
Well look, you've gotta expect that.
You know what you’re dealing with.
#7
Yeah, I suppose.
#10 blows his nose vigorously.
#7
What’s the matter, you got a cold?
#10
And how. These hot weather colds can
kill you.
(he tilts his head back
slightly)
I can hardly touch my nose. Know
what I mean?
#7 nods sympathetically.
#7
I just got over one.
There is an awkward pause. #7 looks at his watch. Then he
looks up at Foreman, who is standing at head of table.
#7
What d’ya say, Mr. Foreman?
MEDIUM SHOT - #7, #10, FOREMAN, #3, #4, FROM ANOTHER ANGLE
Foreman big in foreground, standing at head of table. #7, #10
in background. #3, #4 seated at left at table. Foreman looks
around at the wall clock. #3 leans over to scan #4’s
newspaper.
#3
Anything exciting going on?
#4 looks up at him.

## Step 6: Setting up the LLM
We will load `Qwen3-4B-Instruct-2507`. We load it in `bfloat16` precision to save memory so it fits comfortably on our free Colab GPU.

In [21]:
import torch
from transformers import pipeline

print("Loading LLM...")

model_id = "Qwen/Qwen3-4B-Instruct-2507"

# Set up the text-generation pipeline
llm_pipeline = pipeline(
    "text-generation",
    model=model_id,
    model_kwargs={"dtype": torch.bfloat16},
    device_map="auto"
)

print("LLM Loaded and ready!")

Loading LLM...

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

LLM Loaded and ready!

## Step 7: The Final RAG Pipeline

You have built the retrieval engine and loaded the generator. Now, it is time to tie everything together into a complete Retrieval-Augmented Generation (RAG) pipeline.

In this final step, you will write a function that takes a user's question, fetches the most relevant information from your databases, constructs a prompt for the LLM, and generates a final answer.

**Your Tasks:**
1. **Retrieve Context:** Call your hybrid retrieval function from Step 5 to get the top `k` relevant text chunks for the user's query. Join these chunks into a single, cohesive string.
2. **Design the Prompt:** Large Language Models perform best with clear instructions. You need to construct a message history (a list of dictionaries) containing:
   * A **System Prompt:** Define the AI's persona (e.g., an expert analyzing the movie "12 Angry Men"). Crucially, instruct the AI to answer *only* using the provided context and to cite its sources if possible.
   * A **User Prompt:** Combine the user's actual question with the context string you built in step 1.
3. **Generate Answer:** Pass your message history into your `llm_pipeline`.
   * *Hint:* To keep the model grounded and prevent rambling, configure parameters like `max_new_tokens=150`, `temperature=0.1` (low temperature reduces hallucinations), and `do_sample=True`.
4. **Extract Response:** The Hugging Face pipeline returns a nested structure. You will need to extract just the text of the assistant's final generated reply.

### Expected Outcome
Your function should return a single, coherent text string containing the AI's answer. When you run the test queries at the bottom of the cell, the LLM should accurately answer the questions based exclusively on the retrieved script excerpts.

In [26]:
def ask_rag(query):
    """
    Executes the full RAG pipeline: Retrieves context, builds prompt, and generates an answer.
    """
    print(f"Question: {query}")
    print("Retrieving context...")
    contexts = hybrid_retrieve(query, top_k=3)

    # Join the retrieved chunks into a single string (e.g., separated by newlines)
    context_string = "\n\n---\n\n".join(contexts)

    # 2. Build the prompt
    # Write a strong system prompt directing the AI's behavior
    system_prompt = """You are an expert assistant analyzing the movie "12 Angry Men". You should answer all the questions based exclusively on the provided context and cite your sources. Do not invent facts or adhere to specific formatting requirements. Communicate friendly and formaly.
"""
    # Combine the context and the user's query / Change this as needed to fit your system prompt and the way you want to present the information to the LLM.
    user_prompt = f"Context :\n{context_string}\n\nQuestion: {query}"

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]

    # 3. Generate Answer / You can play with the generation parameters to see how they affect the output. For factual answers, lower temperature and disabling sampling can help.
    outputs = llm_pipeline(
        messages,
        max_new_tokens=150,
        temperature=0.1,
        do_sample=False
    )

    # Extract just the text of the assistant's reply
    final_answer = outputs[0]["generated_text"][-1]["content"]

    return final_answer

## Step 8: Baseline Comparison (LLM Without RAG)

To truly understand the value of our RAG pipeline, we need to see how the Large Language Model performs *without* it.

When you ask a standard LLM a highly specific question, it relies entirely on the knowledge it memorized during its initial training. If it doesn't know the answer, it might guess, hallucinate, or give a vague response.

**Your Task:**
Simply run the cell below. We have provided the `ask_baseline` function for you. This function asks the exact same LLM your question, but it **does not** provide any of the script excerpts from our database.

After running this, try asking both `ask_rag(query)` and `ask_baseline(query)` the same highly specific questions about the script and compare the results!

In [27]:
def ask_baseline(query):
    """
    Queries the LLM directly without any retrieved context (Baseline).
    """
    print(f"Question: {query}")
    print("Generating baseline answer...")

    # 1. Build the prompt without context
    system_prompt = "You are a helpful assistant. Answer the user's question to the best of your ability. The question will be about the movie '12 Angry men' of 1957."

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": query}
    ]

    # 2. Generate Answer
    outputs = llm_pipeline(
        messages,
        max_new_tokens=150,
        temperature=0.1,
        do_sample=False
    )

    # 3. Extract just the text of the assistant's reply
    final_answer = outputs[0]["generated_text"][-1]["content"]
    return final_answer

## Step 9: Evaluating Our System

A crucial part of building AI systems is evaluating them. To do this, we will run both our Baseline LLM and our newly built RAG pipeline against a dataset of predefined questions about "12 Angry Men."

We will compare their answers to the `Correct Answer` provided in our dataset to see how much the retrieved context improves the model's accuracy.

**Your Task:**
Run the evaluation code block below.
* Set `PRINT_RESULTS = True` if you want to watch the models answer the questions in real-time.
* Set `PRINT_RESULTS = False` if you just want it to process everything silently in the background.

The script will automatically test the first question - you can change that variable as you wish. Once it finishes, it will save a new file called `dataset_with_results.csv` containing all the generated answers.

In [28]:
import pandas as pd
from IPython.display import display, Markdown

# ==========================================
# EVALUATION SETTINGS
# ==========================================
# Set this to False if you only want to generate the CSV without printing to the screen
PRINT_RESULTS = True

# Define how many questions to test (e.g., first 5, 10, or len(df_questions) for all)
num_tests = 26
# ==========================================

print("Loading dataset...")
# Load your local dataset
file_path = "dataset.csv"  # Ensure this file is in the same folder as your notebook
df_questions = pd.read_csv(file_path)

print(f"Loaded {len(df_questions)} questions from {file_path}")
if PRINT_RESULTS:
    display(df_questions.head())

# 1. Initialize the new columns in the dataframe if they don't exist
if "simple_rag_answer" not in df_questions.columns:
    df_questions["simple_rag_answer"] = ""
if "baseline_answer" not in df_questions.columns:
    df_questions["baseline_answer"] = ""

# Adjust num_tests just in case the dataset is smaller than requested
num_tests = min(num_tests, len(df_questions))
print(f"\nEvaluating {num_tests} questions. This may take a few minutes...\n")

for index, row in df_questions.head(num_tests).iterrows():
    question = row["Question"]
    expected = row["Correct Answer"]

    # 2. Get answers from both systems for comparison
    baseline_model_answer = ask_baseline(question)
    rag_model_answer = ask_rag(question)

    # 3. Save the answers into the dataframe
    df_questions.at[index, "baseline_answer"] = baseline_model_answer
    df_questions.at[index, "simple_rag_answer"] = rag_model_answer

    # 4. Pretty print the results for real-time monitoring
    if PRINT_RESULTS:
        output = f"""
### Question {index + 1}: {question}

**Expected Answer:**
> {expected}

**Baseline Model Answer (No Context):**
> {baseline_model_answer}

**RAG Model Answer (With Context):**
> {rag_model_answer}

---
"""
        display(Markdown(output))

# 5. Save the updated dataframe to your local CSV
df_questions.to_csv("dataset_with_results.csv", index=False)
print(f"✅ Successfully processed {num_tests} questions and saved to 'dataset_with_results.csv'")

Loading dataset...
Loaded 26 questions from dataset.csv

,Question,Correct Answer,Page References,Explanation
0,What type of train passes by the apartment rig...,An el train (elevated train).,26,This requires retrieving a specific environmen...
1,"According to the boy's alibi, where did he cla...",He claimed to be at the movies.,25,Retrieval of a specific plot point established...
2,What does the sign on the first door of the co...,Court of General Sessions. Part I,3,Fact explicitly stated in the script in the de...
3,What pattern does Juror #3 draw on the same sh...,tic-tac-toe pattern,64,Fact explicitly stated in the script. The info...
4,Which Juror says that he's lived in a slum all...,Juror #5,31,Fact explicitly stated in the script on page 31

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset
Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Evaluating 26 questions. This may take a few minutes...

Question: What type of train passes by the apartment right outside the window where the murder took place?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What type of train passes by the apartment right outside the window where the murder took place?
Retrieving context...

### Question 1: What type of train passes by the apartment right outside the window where the murder took place?

**Expected Answer:**
> An el train (elevated train).

**Baseline Model Answer (No Context):**
> The movie *12 Angry Men* (1957) does not feature a train passing by the apartment outside the window where the murder took place. In fact, the film is set in a New York City courtroom, not in a residential apartment with a view of a train. The story revolves around a jury deliberating the guilt or innocence of a young man accused of murdering his father, and the dynamics among the jurors, not any scenes involving trains or outdoor settings with such details.

Therefore, there is no train in the film that passes by the apartment window—this detail is a fictional or misremembered element not present in the actual movie.

If you're thinking of a different film or a mix-up with another movie, feel free

**RAG Model Answer (With Context):**
> There is no mention of a train passing by the apartment outside the window in the provided context from *12 Angry Men*. The scene descriptions involve discussions about the murder case, the building (such as the Woolworth Building), and the jurors' opinions, but nothing about a train.

Therefore, based on the given text, **no train is mentioned** as passing by the apartment.

**Answer: No train is mentioned.**

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: According to the boy's alibi, where did he claim to be at the time of the murder?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: According to the boy's alibi, where did he claim to be at the time of the murder?
Retrieving context...

### Question 2: According to the boy's alibi, where did he claim to be at the time of the murder?

**Expected Answer:**
> He claimed to be at the movies.

**Baseline Model Answer (No Context):**
> In the 1957 film *12 Angry Men*, the boy's alibi claims that he was at a **movie theater** at the time of the murder. Specifically, he says he was at the theater with his mother and that he saw the film *The Man Who Knew Too Much*. This alibi is presented as evidence to support his claim of not being at the scene of the crime. However, the alibi is later challenged and questioned by the jurors, especially as inconsistencies arise in the details provided.

**RAG Model Answer (With Context):**
> According to the boy's alibi, he claimed to be **at the movies** during the time of the murder.

This is evident in the dialogue on page 25, where #4 says:
*"He claimed he was at the movies during the time of the killing and yet one hour later he couldn’t remember what films he saw, or who played in them."*

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What does the sign on the first door of the corridor say ?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What does the sign on the first door of the corridor say ?
Retrieving context...

### Question 3: What does the sign on the first door of the corridor say ?

**Expected Answer:**
> Court of General Sessions. Part I

**Baseline Model Answer (No Context):**
> The movie *12 Angry Men* (1957) does not feature a sign on the first door of the corridor. The film is set in a jury room, where 12 men discuss the verdict in a murder case, and there are no doors or signs in the corridor as part of the narrative. The setting is a closed, intimate space — a jury room — with no exterior corridor or signage.

Therefore, there is no sign on the first door of the corridor in the film.

If you're thinking of a different movie or a scene from another film, feel free to clarify!

**RAG Model Answer (With Context):**
> The sign on the first door of the corridor says: **"Court of General Sessions. Part I"**.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What pattern does Juror #3 draw on the same sheet of paper upon which Juror #12 has drawn the train?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What pattern does Juror #3 draw on the same sheet of paper upon which Juror #12 has drawn the train?
Retrieving context...

### Question 4: What pattern does Juror #3 draw on the same sheet of paper upon which Juror #12 has drawn the train?

**Expected Answer:**
> tic-tac-toe pattern

**Baseline Model Answer (No Context):**
> There is no such scene in the 1957 film *12 Angry Men* where Juror #3 draws a pattern on the same sheet of paper as Juror #12's train drawing.

In fact, the film does not feature any of the jurors drawing a train or any such pattern. The famous scene involving a drawing is when Juror #8 (not Juror #12) draws a simple diagram of a train to illustrate the possibility of a mistaken interpretation of the evidence — specifically, to show how the defendant's actions could be misunderstood. However, this is a misstatement or confusion in the question.

Juror #12 does not draw a train. The actual drawing in the film is a sketch of a

**RAG Model Answer (With Context):**
> There is no mention in the provided context of Juror #3 drawing anything on the same sheet of paper as Juror #12, nor is there any reference to a "train" being drawn by either juror. Therefore, based on the given text, **no such pattern exists**—the question cannot be answered with the information provided.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: Which Juror says that he's lived in a slum all his life?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: Which Juror says that he's lived in a slum all his life?
Retrieving context...

### Question 5: Which Juror says that he's lived in a slum all his life?

**Expected Answer:**
> Juror #5

**Baseline Model Answer (No Context):**
> In the 1957 film *12 Angry Men*, the juror who says he's lived in a slum all his life is **Juror #8**.

Actually, that's a common misconception. **Juror #8** is the one who initially votes "not guilty" and is the most thoughtful and rational juror. However, he does not say he's lived in a slum.

The juror who *does* say he's lived in a slum is **Juror #3** — a man who claims he grew up in a poor neighborhood and has a strong bias against the defendant because of his background. He says, "I lived in a slum all my life," and uses that experience

**RAG Model Answer (With Context):**
> There is no mention in the provided context of any juror saying that they have lived in a slum all their life. The character descriptions include details about backgrounds such as:

- Juror #11: A refugee from Europe who came to the U.S. in 1941, speaks with an accent, and is humble, ashamed, and subservient due to past suffering and injustice.

However, **there is no explicit statement** in the text that Juror #11 or any other juror says they lived in a slum. While their experience of injustice and hardship is noted, the specific detail about living in a slum is not present.

**Answer: None of the jurors is stated to have said they lived

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What was the length of the old man's bed room?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What was the length of the old man's bed room?
Retrieving context...

### Question 6: What was the length of the old man's bed room?

**Expected Answer:**
> 12 feet

**Baseline Model Answer (No Context):**
> The movie *12 Angry Men* (1957) does not feature a scene or detail about the length of an old man's bedroom. In fact, the film is set in a jury room, not a home, and does not include any character referred to as an "old man" in a bedroom setting. The story centers on a group of jurors discussing the verdict in a murder case, and there is no mention of bedroom dimensions or any such detail.

Therefore, there is no accurate or relevant information about the length of an old man's bedroom in *12 Angry Men*.

If you meant something else—such as a different film or a specific scene—please clarify, and I’d be happy to help!

**RAG Model Answer (With Context):**
> The context provided does not mention the length of the old man's bedroom. There is no information about the size or dimensions of any room, including the old man's bedroom. Therefore, based on the given text, the length of the old man's bedroom cannot be determined.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: According to the seating description, which juror numbers sit in the rear row?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: According to the seating description, which juror numbers sit in the rear row?
Retrieving context...

### Question 7: According to the seating description, which juror numbers sit in the rear row?

**Expected Answer:**
> Jurors #7 through #12.

**Baseline Model Answer (No Context):**
> The 1957 film *12 Angry Men* does not include a detailed seating description that specifies which juror numbers sit in the rear row. In fact, the film is primarily focused on the dynamics of the jury deliberation, not on physical seating arrangements. The characters are not explicitly assigned to specific rows or seats in the courtroom in a way that is documented or referenced in the film’s narrative.

Therefore, based on the available information from the movie, **there is no official or accurate seating description indicating which juror numbers sit in the rear row**.

If you're referring to a specific source, such as a classroom handout, a study guide, or a particular version of the film with a seating chart, that detail might

**RAG Model Answer (With Context):**
> According to the seating description on Page 4, jurors **#7 through #12** sit in the rear row.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What vehicle’s noise is discussed as interfering with hearing testimony?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What vehicle’s noise is discussed as interfering with hearing testimony?
Retrieving context...

### Question 8: What vehicle’s noise is discussed as interfering with hearing testimony?

**Expected Answer:**
> An elevated train (el train), specifically a six-car train.

**Baseline Model Answer (No Context):**
> There is no mention in the 1957 film *12 Angry Men* of any vehicle's noise interfering with hearing testimony. The film is a drama centered on a jury deliberation regarding the guilt or innocence of a young man accused of murdering his father. The focus is on the dynamics among the jurors, their personal biases, and the process of logical reasoning and consensus, not on external auditory distractions like vehicle noise.

Therefore, the question appears to be based on a misunderstanding or a mix-up with another film or context. In *12 Angry Men*, no vehicle noise is discussed as interfering with testimony.

**RAG Model Answer (With Context):**
> There is no mention of a vehicle's noise interfering with hearing testimony in the provided context from *12 Angry Men*. The scene descriptions focus on the courtroom environment, the jury members' interactions, and the atmosphere of the jury room, but there is no reference to vehicle noise or any external sound disrupting testimony.

Therefore, based on the given text, **no vehicle’s noise is discussed as interfering with hearing testimony**.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: How long did the old man claim it took him to reach the door?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: How long did the old man claim it took him to reach the door?
Retrieving context...

### Question 9: How long did the old man claim it took him to reach the door?

**Expected Answer:**
> 15 seconds

**Baseline Model Answer (No Context):**
> The question about how long the old man claimed it took him to reach the door refers to a scene in the 1957 film *12 Angry Men*, but there is no character in the movie known as "the old man" who makes such a claim.

In fact, the film does not feature a character who says anything about taking a certain amount of time to reach a door. The story centers on a jury deliberating the guilt or innocence of a young man accused of murdering his father. The key moments involve discussions about evidence, bias, and the importance of fair judgment — not a specific claim about a person reaching a door.

Therefore, there is no accurate answer to the question as posed — the claim does not exist in the

**RAG Model Answer (With Context):**
> The context provided does not specify how long it took the old man to reach the door of his apartment. It only states that he "ran to the door of his apartment, looked out, and saw the kid running down the stairs and out of the house." There is no mention of the time it took him to reach the door.

Therefore, based on the given text, **the duration is not stated**.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What weapon was used in the murder?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What weapon was used in the murder?
Retrieving context...

### Question 10: What weapon was used in the murder?

**Expected Answer:**
> A knife

**Baseline Model Answer (No Context):**
> In the 1957 film *12 Angry Men*, the weapon used in the murder is a **rope**. The victim, a young man, was strangled with a rope. This detail is revealed during the course of the trial as the jury members discuss the evidence and the circumstances of the crime. The rope is a key piece of evidence that helps establish the method of the murder, and its significance is explored in the context of the trial's deliberations.

**RAG Model Answer (With Context):**
> The context provided does not mention what weapon was used in the murder. Therefore, based on the given text, the weapon used in the murder cannot be determined.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What does Juror #5 say when he discovers the jury room door is locked?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What does Juror #5 say when he discovers the jury room door is locked?
Retrieving context...

### Question 11: What does Juror #5 say when he discovers the jury room door is locked?

**Expected Answer:**
> He says 'I never knew they locked the door.'

**Baseline Model Answer (No Context):**
> In the 1957 film *12 Angry Men*, when Juror #5 discovers that the jury room door is locked, he says:

**"This is a trick. This is a trick!"**

He is initially shocked and suspicious, believing the door should have been unlocked or that the situation is being manipulated. His reaction reflects his strong sense of fairness and his distrust of any attempt to control or deceive the jury. This moment highlights his integrity and sets the stage for the growing tension and discussion that follows as the jurors begin to question the validity of the trial and the evidence.

**RAG Model Answer (With Context):**
> The provided context does not include what Juror #5 says when he discovers the jury room door is locked. Therefore, based on the given text, that specific detail cannot be answered.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What game does Juror #7 have tickets for?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What game does Juror #7 have tickets for?
Retrieving context...

### Question 12: What game does Juror #7 have tickets for?

**Expected Answer:**
> A baseball game, Yankees vs Cleveland.

**Baseline Model Answer (No Context):**
> In the 1957 film *12 Angry Men*, Juror #7 does not have tickets for any game. This detail is not part of the movie's plot or dialogue. The film is a classic drama about a jury deliberating the guilt or innocence of a young man accused of murdering his father. It focuses on themes of justice, prejudice, and human behavior, not on any specific games or tickets.

Therefore, there is no accurate information in the film suggesting that Juror #7 has tickets for a game. The question may be based on a misunderstanding or a mix-up with another film or context.

Answer: Juror #7 does not have tickets for any game in *12 Angry Men*.

**RAG Model Answer (With Context):**
> There is no mention of Juror #7 having tickets for any game in the provided context. The information given describes Juror #7 as a loud, flashy, and impatient man who is quick to form opinions and show temper, but nothing about tickets or a specific event like a game is referenced.

Therefore, based on the context provided, **we cannot determine what game Juror #7 has tickets for** — it is not mentioned at all.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What is the name of the breakfast cereal Juror #12 doodles, and what is its advertising slogan?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What is the name of the breakfast cereal Juror #12 doodles, and what is its advertising slogan?
Retrieving context...

### Question 13: What is the name of the breakfast cereal Juror #12 doodles, and what is its advertising slogan?

**Expected Answer:**
> The cereal is **Rice Pops**, and the slogan is **The Breakfast With The Built-In Bounce**

**Baseline Model Answer (No Context):**
> There is no breakfast cereal that Juror #12 doodles in the 1957 film *12 Angry Men*. This detail is a fictional or misremembered element not present in the actual movie.

In *12 Angry Men*, Juror #12 (played by Henry Fonda) is a thoughtful, initially skeptical man who gradually becomes convinced of the defendant's innocence. The film is a classic drama about jury deliberation and the power of reason, empathy, and logic — it does not include any scenes involving breakfast cereals or advertising slogans.

The idea of Juror #12 doodling a cereal may stem from a confusion with another film, a parody, or a mix-up with a different movie or cultural reference

**RAG Model Answer (With Context):**
> The context provided does not mention anything about a breakfast cereal or an advertising slogan associated with Juror #12. While Juror #12 is described as an "advertising man" who thinks in terms of percentages, graphs, and polls, and who doodles on a scratch pad, there is no information given about the specific cereal he doodles or its slogan.

Therefore, based on the provided text, **the name of the breakfast cereal and its advertising slogan cannot be determined**.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: How much did the replica switchblade knife cost when it was purchased at the pawnshop?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: How much did the replica switchblade knife cost when it was purchased at the pawnshop?
Retrieving context...

### Question 14: How much did the replica switchblade knife cost when it was purchased at the pawnshop?

**Expected Answer:**
> Two Dollars

**Baseline Model Answer (No Context):**
> The replica switchblade knife mentioned in the context of *12 Angry Men* (1957) is not a real item from the film. In the movie, there is no scene involving a switchblade knife being purchased at a pawnshop. The film is a drama about a jury deliberating the guilt or innocence of a young man accused of murdering his father, and it focuses on themes of justice, prejudice, and logic—not on physical objects like knives.

Therefore, the replica switchblade knife did not exist in the film, and there is no record or mention of its cost when purchased at a pawnshop.

If you're referring to a different film, a real-life incident, or a misremembered detail, feel free to clarify

**RAG Model Answer (With Context):**
> The context provided does not mention the cost of the replica switchblade knife purchased at the pawnshop. Therefore, based on the given text, the cost is not available.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What is the name of the high school where the Foreman works as an assistant head football coach?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What is the name of the high school where the Foreman works as an assistant head football coach?
Retrieving context...

### Question 15: What is the name of the high school where the Foreman works as an assistant head football coach?

**Expected Answer:**
> Andrew J. McCorkle High School

**Baseline Model Answer (No Context):**
> The movie *12 Angry Men* (1957) does not feature a high school or a foreman working as an assistant head football coach. In fact, the film is a drama centered around a jury deliberation in a murder trial, not a school or coaching setting. The characters are a group of jurors, and there is no mention of a high school or a football coach in the story.

Therefore, there is no such high school in *12 Angry Men* — the premise of your question appears to be based on a misunderstanding or a mix-up with another film.

If you were thinking of a different movie, feel free to clarify!

**RAG Model Answer (With Context):**
> The context provided does not mention the name of the high school where the Foreman works as an assistant head football coach. Therefore, based on the given information, the name of the high school cannot be determined.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: Who was the first of the jurymen to go to the men's room?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: Who was the first of the jurymen to go to the men's room?
Retrieving context...

### Question 16: Who was the first of the jurymen to go to the men's room?

**Expected Answer:**
> Juror #9

**Baseline Model Answer (No Context):**
> There is no specific mention in the 1957 film *12 Angry Men* of any juror going to the men's room, and the film does not include such a detail. The story focuses on the deliberations of the 12 jurors as they debate the guilt or innocence of the defendant, and the narrative centers on their interactions, biases, and evolving perspectives—particularly through the influence of Juror #8.

The scene where a juror goes to the men's room is not part of the original screenplay or film. Therefore, **no juror is identified as the first to go to the men's room** in the movie.

If you're thinking of a specific scene or a misremembered detail, it might

**RAG Model Answer (With Context):**
> The context provided does not mention anyone going to the men's room or specify who was the first jurymen to do so. Therefore, based on the given text, **we cannot determine who was the first jurymen to go to the men's room**.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: How old is Juror #9?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: How old is Juror #9?
Retrieving context...

### Question 17: How old is Juror #9?

**Expected Answer:**
> 70 years old

**Baseline Model Answer (No Context):**
> In the 1957 film *12 Angry Men*, Juror #9's age is not explicitly stated in the movie. The film focuses more on the dynamics of the jury members and their reasoning during the deliberation than on their personal details like age. Therefore, Juror #9's exact age is not provided in the film.

**RAG Model Answer (With Context):**
> Juror #9 is 70 years old.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What job does Juror #6 have?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: What job does Juror #6 have?
Retrieving context...

### Question 18: What job does Juror #6 have?

**Expected Answer:**
> Housepainter

**Baseline Model Answer (No Context):**
> In the 1957 film *12 Angry Men*, Juror #6 is a **man who works as a factory worker**. He is portrayed as a thoughtful and reasonable juror who initially has a skeptical attitude toward the prosecution's case but gradually becomes more convinced of the defendant's innocence as the discussion progresses. His background as a working-class individual adds to the film's exploration of social class and prejudice.

**RAG Model Answer (With Context):**
> Juror #6 is a **housepainter**.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: According to the script, which jurors sit in the front row of the jury box?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: According to the script, which jurors sit in the front row of the jury box?
Retrieving context...

### Question 19: According to the script, which jurors sit in the front row of the jury box?

**Expected Answer:**
> Jurors #1, #2, #3, #4, #5 and #6 sit in the front row

**Baseline Model Answer (No Context):**
> In the 1957 film *12 Angry Men*, the script does not explicitly assign specific jurors to sit in the front row of the jury box in a way that is formally documented or emphasized. However, in the film's visual presentation, the jurors are arranged in a traditional jury box setup, with the front row typically occupied by the more vocal or influential members.

According to the script and the film's narrative, **Juror #8 (played by Henry Fonda)** is often seen sitting in the front row, and he is the one who initially votes "not guilty" and begins the process of questioning the evidence. His position in the front row symbolizes his leadership and influence throughout the deliberations.

While the script doesn't

**RAG Model Answer (With Context):**
> According to the script, the jurors who sit in the front row of the jury box are **#1 through #6**.

This is explicitly stated in the text on Page 4:

> "The jury sits in numerical order reading from left to right: the through #6 in the front row, #7–#12 in the rear row."

(Note: "the through #6" is a typo or misphrasing — it should read "through #6" meaning up to #6.)

Therefore, jurors #1 to #6 are in the front row.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: Where is Juror #11 from ?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: Where is Juror #11 from ?
Retrieving context...

### Question 20: Where is Juror #11 from ?

**Expected Answer:**
> Europe

**Baseline Model Answer (No Context):**
> In the 1957 film *12 Angry Men*, Juror #11 is from **New York City**. He is portrayed as a man who is initially dismissive of the jury process and is skeptical of the evidence, particularly the testimony of the young man accused of the crime. His background as a New Yorker is highlighted in the film, and he is shown to be somewhat impatient and critical of the deliberations. However, it's worth noting that the film is a dramatization, and the character's specific origin is not explicitly detailed beyond his New York roots.

**RAG Model Answer (With Context):**
> Juror #11 is from Europe.

This is stated in the context: "Juror #11: 48 years old. Watchmaker. A refugee from Europe who has come to this country in 1941."

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: Is Juror #4 wealthy ?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: Is Juror #4 wealthy ?
Retrieving context...

### Question 21: Is Juror #4 wealthy ?

**Expected Answer:**
> Yes

**Baseline Model Answer (No Context):**
> No, Juror #4 is not wealthy in the 1957 film *12 Angry Men*. In fact, Juror #4 is portrayed as a middle-class man who is a retired factory worker. His background is modest, and he is known for being thoughtful, logical, and deeply concerned about the fairness of the verdict. His strong sense of justice and skepticism about the evidence stem more from his personal integrity and experience than from wealth. The film emphasizes his rationality and empathy rather than any indication of financial status.

**RAG Model Answer (With Context):**
> Yes, Juror #4 is wealthy.

This is explicitly stated in the character description: *"Juror #4: 50 years old. Stockbroker. A man of wealth and position."*

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: Has Juror #2 been on jury before ?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: Has Juror #2 been on jury before ?
Retrieving context...

### Question 22: Has Juror #2 been on jury before ?

**Expected Answer:**
> No

**Baseline Model Answer (No Context):**
> In the 1957 film *12 Angry Men*, there is no explicit information suggesting that Juror #2 has been on a jury before. The film focuses on the dynamics and interactions among the 12 jurors as they deliberate the case, and Juror #2 (played by Lee J. Cobb) is portrayed as a man who is initially skeptical and resistant to the idea of a guilty verdict. However, his background is not detailed in a way that confirms prior jury service.

In fact, the film deliberately keeps the personal backgrounds of the jurors vague or minimal, emphasizing their individual biases, emotions, and reasoning during the deliberation. Juror #2 is more characterized by his strong sense of duty and his initial belief in the

**RAG Model Answer (With Context):**
> No, there is no information in the provided context indicating that Juror #2 has been on a jury before.

The character description for Juror #2 states: *"38 years old. Bank clerk. A meek, hesitant man who finds it difficult to maintain any opinions of his own. Easily swayed and usually adopts the opinion of the last person to idiom he has spoken."*

However, this description focuses on his personality and behavior during the deliberation process, not on any prior jury experience. Therefore, based on the given text, we cannot determine whether Juror #2 has been on a jury before.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: In the movie 12 Angry Men, how many seconds after the body fell did the old man witness claim he needed to reach the door and see the boy run out?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: In the movie 12 Angry Men, how many seconds after the body fell did the old man witness claim he needed to reach the door and see the boy run out?
Retrieving context...

### Question 23: In the movie 12 Angry Men, how many seconds after the body fell did the old man witness claim he needed to reach the door and see the boy run out?

**Expected Answer:**
> 15 seconds.

**Baseline Model Answer (No Context):**
> The movie *12 Angry Men* (1957) does not include a specific detail about how many seconds after the body fell the old man claimed he needed to reach the door and see the boy run out. In fact, this particular detail—such as a precise time measurement of seconds—is not part of the film's narrative.

The story centers on a jury deliberation over the guilt of a young man accused of murdering his father. The key moments involve the jury members discussing the evidence, the credibility of the testimony, and the importance of fair judgment. The old man (Juror 8) does not make a claim about seconds after a body fell or a boy running out. That scenario appears to be a misstatement or confusion

**RAG Model Answer (With Context):**
> The provided context does not specify how many seconds after the body fell the old man claimed he needed to reach the door and see the boy run out. The text mentions that the old man heard the body fall and then ran to the door, but it does not include a specific time interval (in seconds) between the fall and his action of looking out.

Therefore, based on the given information, **the exact number of seconds is not stated**.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: Which juror acts as if he has a cold?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: Which juror acts as if he has a cold?
Retrieving context...

### Question 24: Which juror acts as if he has a cold?

**Expected Answer:**
> Juror #10.

**Baseline Model Answer (No Context):**
> In the 1957 film *12 Angry Men*, the juror who acts as if he has a cold is **Juror #8**.

Actually, that’s a common misconception. Let's clarify:

Juror #8 — the one who initially votes "not guilty" — does **not** act as if he has a cold. Instead, **Juror #3** is the one who acts as if he has a cold.

Juror #3 is a man who is visibly uncomfortable and often pretends to have a cold or a sore throat, especially when he is trying to avoid confrontation or when he is being defensive. He is also shown to be somewhat dismissive and resistant to the others' arguments, and his

**RAG Model Answer (With Context):**
> Juror #10 acts as if he has a cold.

This is stated in the character description on Page 2:
"Juror #10: 46 years old. Garage owner. An angry, bitter man. A man who antagonizes almost at sight. A bigot who places no values on any human life save his own. A man who has been no where and is going nowhere and knows it deep within him. He has a bad cold and continually blows his nose, sniffs a benzedrine inhaler, etc."

Thus, Juror #10 is the one who has a bad cold and exhibits cold-related behaviors.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: According to the script, what is the occupation of Juror #3?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: According to the script, what is the occupation of Juror #3?
Retrieving context...

### Question 25: According to the script, what is the occupation of Juror #3?

**Expected Answer:**
> He runs a messenger service called 'Beck and Call'.

**Baseline Model Answer (No Context):**
> According to the script of *12 Angry Men* (1957), Juror #3 is a **man who works in a factory**. He is described as a man who is "a little bit of a show-off" and is initially dismissive of the importance of the trial, but he is also shown to be a man of some experience and practicality. However, the script does not specify the exact type of factory work. His occupation is generally referred to as a factory worker, and he is not given a more detailed or specific job title.

**RAG Model Answer (With Context):**
> According to the script, the occupation of Juror #3 is **head of messenger service**.

---

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: How old is Juror #3 and what is his occupation?
Generating baseline answer...

Both `max_new_tokens` (=150) and `max_length`(=20) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Question: How old is Juror #3 and what is his occupation?
Retrieving context...

### Question 26: How old is Juror #3 and what is his occupation?

**Expected Answer:**
> 40 years old. Head of a messenger service.

**Baseline Model Answer (No Context):**
> In the 1957 film *12 Angry Men*, Juror #3 is portrayed as a man in his 50s. He is approximately 50 years old. His occupation is a **retired factory worker**.

Juror #3 is known for being a strict, rigid, and initially dismissive juror who is deeply committed to the idea that the defendant is guilty. He is also shown to be somewhat prejudiced and resistant to change, which makes his eventual shift in perspective a key part of the film's theme of rational discussion and reevaluation of evidence.

**RAG Model Answer (With Context):**
> Juror #3 is 40 years old and works as the head of a messenger service.

---

✅ Successfully processed 26 questions and saved to 'dataset_with_results.csv'